run_id: brain-tumor-exp01
data:
  image_size: 224
  train_in: data/training
  val_frac: 0.2
  batch_size: 32
  num_workers: 4
  seed: 42
model:
  name: resnet18
  pretrained: true
optim:
  lr: 0.001
  weight_decay: 0.0001
  step_size: 10
  gamma: 0.1
  amp: true
io:
  out_models: models
  out_summary: outputs/training